http://scikit-learn.org/stable/auto_examples/linear_model/plot_logistic_l1_l2_sparsity.html

In [1]:
import numpy as np
import matplotlib.pyplot as plt

from sklearn.linear_model import LogisticRegression
from sklearn import datasets
from sklearn.preprocessing import StandardScaler

In [2]:
?LogisticRegression

In [9]:
digits = datasets.load_digits()
X, y = digits.data, digits.target

In [10]:
# комментарии

In [11]:
X = StandardScaler().fit_transform(X)
X[:1]

array([[ 0.        , -0.33501649, -0.04308102,  0.27407152, -0.66447751,
        -0.84412939, -0.40972392, -0.12502292, -0.05907756, -0.62400926,
         0.4829745 ,  0.75962245, -0.05842586,  1.12772113,  0.87958306,
        -0.13043338, -0.04462507,  0.11144272,  0.89588044, -0.86066632,
        -1.14964846,  0.51547187,  1.90596347, -0.11422184, -0.03337973,
         0.48648928,  0.46988512, -1.49990136, -1.61406277,  0.07639777,
         1.54181413, -0.04723238,  0.        ,  0.76465553,  0.05263019,
        -1.44763006, -1.73666443,  0.04361588,  1.43955804,  0.        ,
        -0.06134367,  0.8105536 ,  0.63011714, -1.12245711, -1.06623158,
         0.66096475,  0.81845076, -0.08874162, -0.03543326,  0.74211893,
         1.15065212, -0.86867056,  0.11012973,  0.53761116, -0.75743581,
        -0.20978513, -0.02359646, -0.29908135,  0.08671869,  0.20829258,
        -0.36677122, -1.14664746, -0.5056698 , -0.19600752]])

In [12]:
y

array([0, 1, 2, ..., 8, 9, 8])

In [13]:
y = (y > 4).astype(np.int)
y

array([0, 0, 0, ..., 1, 1, 1])

In [19]:
for i, C in enumerate((100, 1, 0.01)):
    print( i, C )

0 100
1 1
2 0.01


In [17]:
for i, C in enumerate((100, 1, 0.01)):
    clf_l1_LR = LogisticRegression(C=C, penalty='l1', tol=0.01)
    clf_l2_LR = LogisticRegression(C=C, penalty='l2', tol=0.01)
    
    clf_l1_LR.fit(X, y)
    clf_l2_LR.fit(X, y)
    
    # коэффициенты признаков
    coef_l1_LR = clf_l1_LR.coef_.ravel()
    coef_l2_LR = clf_l2_LR.coef_.ravel()
    
    print("score with L1 penalty: %.4f" % clf_l1_LR.score(X, y))
    print("score with L2 penalty: %.4f" % clf_l2_LR.score(X, y))

score with L1 penalty: 0.9098
score with L2 penalty: 0.9098
score with L1 penalty: 0.9087
score with L2 penalty: 0.9093
score with L1 penalty: 0.8631
score with L2 penalty: 0.8915


In [ ]:
?L